### ISSUE TITLE
[Feature] Allow the use of `:host` in variable definitions

### ISSUE THREAD

**Issue by fabiiomiiguel** [oruga-ui/theme-oruga#32]
I'm currently using web components with `Vue 3`, `oruga-ui` and `theme-oruga`.

With the release `3.0.0` the variables stop working correctly because the web components rely on `shadow-dom`, which doesn't use the `:root` selector.

I created a [pull request](https://github.com/oruga-ui/theme-oruga/pull/31) to allow the usage of `:host` for web components.

This code was based on this [pull request](https://github.com/twbs/bootstrap/pull/38056) from bootstrap.

What do you think?

**Comment by mlmoravek** [comment]
Nice! Thanks for the improvement :) Will be released soon!
