### ISSUE TITLE
Border-radius typo within Slider styles

### ISSUE THREAD

**Issue by Nik-Weightmans** [oruga-ui/theme-oruga#62]
Please refer to the below (needs to be comma separated)

https://github.com/oruga-ui/theme-oruga/blob/1f8d8338d27f956e7d463b14093154f998d41a79/src/assets/scss/components/_slider.scss#L134

![2024-07-26_11h52_22](https://github.com/user-attachments/assets/a813a345-f609-44a8-ba57-581d517dcd4d)

**Comment by mlmoravek** [comment]
Thanks for discovering this!
